from figstyle import plt, np, save, C

t = np.linspace(0, 2, 4000)
f1, f2 = 10, 11
y1 = np.sin(2 * np.pi * f1 * t)
y2 = np.sin(2 * np.pi * f2 * t)
fig, (a1, a2) = plt.subplots(2, 1, figsize=(6.6, 3.7), sharex=True)
a1.plot(t, y1, color=C["blue"], lw=0.9, label="10 Hz")
a1.plot(t, y2, color=C["red"], lw=0.9, alpha=0.8, label="11 Hz")
a1.set_yticks([])
a1.set_ylim(-1.2, 2.2)
a1.legend(fontsize=8.5, ncol=2, loc="upper right", borderaxespad=0.1)
a1.set_title("진폭이 같고 주파수가 조금 다른 두 사인파", fontsize=10, loc="left")
a2.plot(t, y1 + y2, color=C["ink"], lw=0.9)
env = 2 * np.abs(np.cos(np.pi * (f2 - f1) * t))
a2.plot(t, env, color=C["purple"], lw=1, ls="--")
a2.plot(t, -env, color=C["purple"], lw=1, ls="--")
a2.set_yticks([])
a2.set_ylim(-3.0, 3.0)
a2.annotate("", xy=(0.0, 2.45), xytext=(1.0, 2.45), arrowprops=dict(arrowstyle="<->", color=C["purple"]))
a2.text(0.5, 2.5, "맥놀이 주기 1 s = 1/(11 − 10 Hz)", ha="center", va="bottom", fontsize=8.5, color=C["purple"])
a2.text(0.5, -2.25, "상쇄", ha="center", va="top", fontsize=8.5, color=C["gray"])
a2.text(1.0, -2.25, "보강", ha="center", va="top", fontsize=8.5, color=C["gray"])
a2.set_title("두 파의 합", fontsize=10, loc="left")
a2.set_xlabel("시간 (s)")
fig.tight_layout()
save(fig, __file__)
